# Copyright (c) 2020-2021 Afterpay Corporate Services Pty Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# See https://help.github.com/en/actions/configuring-and-managing-workflows
# See https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Integration Test

on:
  push:
    branches:
      - main
      - 'release/**'
    paths-ignore:
      - 'README.md'
      - 'sample.env.php'
      - '.gitignore'
  pull_request:
    branches:
      - main
      - 'release/**'
    paths-ignore:
      - 'README.md'
      - 'sample.env.php'
      - '.gitignore'

# Note: For information on the `ubuntu-latest` base image, see:
# https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md

jobs:
  oceania:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        country-code: [ 'AU', 'NZ' ]
      fail-fast: false
      max-parallel: 1

    name: ${{ matrix.country-code }} Sandbox

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/test-integration
        with:
          country-code: ${{ matrix.country-code }}
          merchant-id: ${{ secrets[ format('{0}_SBOX_MID_1', matrix.country-code) ] }}
          secret-key: ${{ secrets[ format('{0}_SBOX_SKEY_1', matrix.country-code) ] }}
          consumer-email: ${{ secrets[ format('{0}_SBOX_CONSUMER_EMAIL_1', matrix.country-code) ] }}
          consumer-password: ${{ secrets[ format('{0}_SBOX_CONSUMER_PASSWORD_1', matrix.country-code) ] }}
  north-america:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        country-code: [ 'CA', 'US' ]
      fail-fast: false
      max-parallel: 1

    name: ${{ matrix.country-code }} Sandbox

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/test-integration
        with:
          country-code: ${{ matrix.country-code }}
          merchant-id: ${{ secrets[ format('{0}_SBOX_MID_1', matrix.country-code) ] }}
          secret-key: ${{ secrets[ format('{0}_SBOX_SKEY_1', matrix.country-code) ] }}
          consumer-email: ${{ secrets[ format('{0}_SBOX_CONSUMER_EMAIL_1', matrix.country-code) ] }}
          consumer-password: ${{ secrets[ format('{0}_SBOX_CONSUMER_PASSWORD_1', matrix.country-code) ] }}
  europe:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        country-code: [ 'UK' ] # To-do: Replace UK secrets with GB secrets
      fail-fast: false
      max-parallel: 1

    name: ${{ matrix.country-code }} Sandbox

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/test-integration
        with:
          country-code: ${{ matrix.country-code }}
          merchant-id: ${{ secrets[ format('{0}_SBOX_MID_1', matrix.country-code) ] }}
          secret-key: ${{ secrets[ format('{0}_SBOX_SKEY_1', matrix.country-code) ] }}
          consumer-email: ${{ secrets[ format('{0}_SBOX_CONSUMER_EMAIL_1', matrix.country-code) ] }}
          consumer-password: ${{ secrets[ format('{0}_SBOX_CONSUMER_PASSWORD_1', matrix.country-code) ] }}
  cross-border-trade-uk:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        consumer-country-code: [ 'UK' ]
        merchant-country-code: [ 'US', 'CA', 'NZ', 'AU' ]
      fail-fast: false
      max-parallel: 1

    name: CBT - ${{ matrix.consumer-country-code }} consumer, ${{ matrix.merchant-country-code }} merchant

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/test-cbt
        with:
          merchant-id: ${{ secrets[ format('{0}_SBOX_MID_1', matrix.merchant-country-code) ] }}
          secret-key: ${{ secrets[ format('{0}_SBOX_SKEY_1', matrix.merchant-country-code) ] }}
          merchant-country-code: ${{ matrix.merchant-country-code }}
          consumer-email: ${{ secrets[ format('{0}_SBOX_CONSUMER_EMAIL_CBT', matrix.consumer-country-code) ] }}
          consumer-password: ${{ secrets[ format('{0}_SBOX_CONSUMER_PASSWORD_CBT', matrix.consumer-country-code) ] }}
          consumer-country-code: ${{ matrix.consumer-country-code }}
  cross-border-trade-us:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        consumer-country-code: [ 'US' ]
        merchant-country-code: [ 'UK', 'CA', 'NZ', 'AU' ]
      fail-fast: false
      max-parallel: 1

    name: CBT - ${{ matrix.consumer-country-code }} consumer, ${{ matrix.merchant-country-code }} merchant

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/test-cbt
        with:
          merchant-id: ${{ secrets[ format('{0}_SBOX_MID_1', matrix.merchant-country-code) ] }}
          secret-key: ${{ secrets[ format('{0}_SBOX_SKEY_1', matrix.merchant-country-code) ] }}
          merchant-country-code: ${{ matrix.merchant-country-code }}
          consumer-email: ${{ secrets[ format('{0}_SBOX_CONSUMER_EMAIL_CBT', matrix.consumer-country-code) ] }}
          consumer-password: ${{ secrets[ format('{0}_SBOX_CONSUMER_PASSWORD_CBT', matrix.consumer-country-code) ] }}
          consumer-country-code: ${{ matrix.consumer-country-code }}
  cross-border-trade-ca:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        consumer-country-code: [ 'CA' ]
        merchant-country-code: [ 'UK', 'US', 'NZ', 'AU' ]
      fail-fast: false
      max-parallel: 1

    name: CBT - ${{ matrix.consumer-country-code }} consumer, ${{ matrix.merchant-country-code }} merchant

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/test-cbt
        with:
          merchant-id: ${{ secrets[ format('{0}_SBOX_MID_1', matrix.merchant-country-code) ] }}
          secret-key: ${{ secrets[ format('{0}_SBOX_SKEY_1', matrix.merchant-country-code) ] }}
          merchant-country-code: ${{ matrix.merchant-country-code }}
          consumer-email: ${{ secrets[ format('{0}_SBOX_CONSUMER_EMAIL_CBT', matrix.consumer-country-code) ] }}
          consumer-password: ${{ secrets[ format('{0}_SBOX_CONSUMER_PASSWORD_CBT', matrix.consumer-country-code) ] }}
          consumer-country-code: ${{ matrix.consumer-country-code }}
  cross-border-trade-nz:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        consumer-country-code: [ 'NZ' ]
        merchant-country-code: [ 'UK', 'US', 'CA', 'AU' ]
      fail-fast: false
      max-parallel: 1

    name: CBT - ${{ matrix.consumer-country-code }} consumer, ${{ matrix.merchant-country-code }} merchant

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/test-cbt
        with:
          merchant-id: ${{ secrets[ format('{0}_SBOX_MID_1', matrix.merchant-country-code) ] }}
          secret-key: ${{ secrets[ format('{0}_SBOX_SKEY_1', matrix.merchant-country-code) ] }}
          merchant-country-code: ${{ matrix.merchant-country-code }}
          consumer-email: ${{ secrets[ format('{0}_SBOX_CONSUMER_EMAIL_CBT', matrix.consumer-country-code) ] }}
          consumer-password: ${{ secrets[ format('{0}_SBOX_CONSUMER_PASSWORD_CBT', matrix.consumer-country-code) ] }}
          consumer-country-code: ${{ matrix.consumer-country-code }}
  cross-border-trade-au:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        consumer-country-code: [ 'AU' ]
        merchant-country-code: [ 'UK', 'US', 'CA', 'NZ' ]
      fail-fast: false
      max-parallel: 1

    name: CBT - ${{ matrix.consumer-country-code }} consumer, ${{ matrix.merchant-country-code }} merchant

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/test-cbt
        with:
          merchant-id: ${{ secrets[ format('{0}_SBOX_MID_1', matrix.merchant-country-code) ] }}
          secret-key: ${{ secrets[ format('{0}_SBOX_SKEY_1', matrix.merchant-country-code) ] }}
          merchant-country-code: ${{ matrix.merchant-country-code }}
          consumer-email: ${{ secrets[ format('{0}_SBOX_CONSUMER_EMAIL_CBT', matrix.consumer-country-code) ] }}
          consumer-password: ${{ secrets[ format('{0}_SBOX_CONSUMER_PASSWORD_CBT', matrix.consumer-country-code) ] }}
          consumer-country-code: ${{ matrix.consumer-country-code }}
